### ISSUE TITLE
Too many bugs in Ubuntu18.04 

### ISSUE THREAD

**Issue by chenchaohan** [Lin-Buo-Ren/OpenSyobonAction-snap#7]
There are too many bugs in ubuntu18.04  
you can't not predicate where will comes out bugs 
I don't know how to upload pictures for you

**Comment by Lin-Buo-Ren** [comment]
Apologies for the ignorance, without the bug reproduction instructions I am unable to do anything to fix your problems, if it's still relevant please file a new issue, thanks!
